const availableCourses = [
    'CS521 - Information Structures with Python',
    'CS526 - Data Structure and Algorithms',
    'CS622 - Advanced Programming Techniques',
    'CS665 - Software Design and Patterns',
    'CS673 - Software Engineering',
    'CS682 - Information Systems Analysis and Design',
    'CS601 - Web Application Development',
    'CS602 - Server-Side Web Development',
    'CS633 - Software Quality, Testing, and Security Management',
    'CS634 - Agile Software Development',
    'CS664 - Artificial Intelligence',
    'CS669 - Database Design and Implementation for Business',
    'CS677 - Data Science with Python',
    'CS683 - Mobile Application Development with Android',
    'CS701 - Rich Internet Application Development',
    'CS763 - Secure Software Development',
    'CS767 - Advance Machine Learning and Neural Networks',
    'CS101 - Computers and Their Applications',
    'CS200 - Introduction to Computer Information Systems',
    'CS201 - Introduction to Programming',
    'CS231 - Programming with C++',
    'CS232 - Programming with Java',
    'CS248 - Discrete Mathematics',
    'CS300 - Introduction to Software Development',
    'CS341 - Data Structure with C++',
    'CS342 - Data Structures with Java',
    'CS382 - Information Systems for Management',
    'CS401 - Introduction to Web Application Development',
    'CS422 - Advanced Programming Concepts',
    'CS425 - Introduction to Business Data Communications and Networks',
    'CS432 - Introduction to IT Project Management',
    'CS469 - Introduction to Database Design and Implementation for Business',
    'CS472 - Computer Architecture',
    'CS473 - Introduction to Software Engineering',
    'CS495 - Directed Study',
    'CS496 - Directed Study',
    'CS506 - Internship in Computer Science',
    'CS520 - Information Structures with Java',
    'CS532 - Computer Graphics',
    'CS535 - Computer Networks',
    'CS544 - Foundations of Analytics and Data Visualization',
    'CS546 - Introduction to Probability and Statistics',
    'CS550 - Computational Mathematics for Machine Learning',
    'CS555 - Foundation of Machine Learning',
    'CS561 - Financial Analytics',
    'CS566 - Analysis of Algorithms',
    'CS570 - Biomedical Sciences and Health IT',
    'CS575 - Operating Systems',
    'CS579 - Database Management',
    'CS580 - Health Informatics',
    'CS581 - Health Information Systems',
    'CS584 - Ethical and Legal Issues in Healthcare Informatics',
    'CS593 - Special Topics',
    'CS599 - Biometrics',
    'CS625 - Business Data Communication and Networks',
    'CS632 - Information Technology Project Management',
    'CS662 - Computer Language Theory',
    'CS674 - Database Security',
    'CS684 - Enterprise Cybersecurity Management',
    'CS685 - Network Design and Management',
    'CS688 - Web Mining and Graph Analytics',
    'CS689 - Designing and Implementing a Data Warehouse',
    'CS690 - Network Security',
    'CS693 - Digital Forensics and Investigations',
    'CS694 - Mobile Forensics and Security',
    'CS695 - Cybersecurity',
    'CS697 - Special Topics in Computer Science',
    'CS699 - Data Mining',
    'CS775 - Advanced Networking',
    'CS777 - Big Data Analytics',
    'CS779 - Advance Database Management',
    'CS781 - Advanced Health Informatics',
    'CS782 - IT Strategy and Management',
    'CS783 - Enterprise Architecture',
    'CS789 - Cryptography',
    'CS793 - Special Topics in Computer Science',
    'CS795 - Directed Study',
    'CS796 - Directed Study',
    'CS799 - Advance Cryptography',
    'CS766 - Deep Reinforcement Learning',
    'CS787 - Adversarial Machine Learning',
    'CS788 - Generative AI',
    'CS790 - Computer Vision in AI',
    'CS810 - Master\'s Thesis in Computer Science',
    'CS811 - Master\'s Thesis in Computer Science',
    'CS703 - Network Forensics',
    'CS635 - Network Media Technologies'
];

export default availableCourses;