services:
  ai-api:
    build:
      context: .  # Path to the Dockerfile directory
      dockerfile: Dockerfile
    image: buan-api:1.0.1
    ports:
      - "9080:9080"
    env_file:
      - .env
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "9080"]
